version: "3.9"

services:
  telescreen:
    image: wide-vsix/telescreen:latest
    restart: unless-stopped
    build:
      context: .
    network_mode: host
    depends_on:
      - postgres
    command: -i vsix -A -q --db-host postgres --db-name telescreen --db-user vsix --db-password-file /run/secrets/db_password
    secrets:
      - db_password

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      ipv6_gw:
      default:
    environment:
      POSTGRES_DB: telescreen
      POSTGRES_USER: vsix
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      TZ: "Asia/Tokyo"
    secrets:
      - db_password
    volumes:
      - psql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5050:80
    networks:
      ipv6_gw:
      default:
    environment:
      PGADMIN_DEFAULT_EMAIL: vsix@vsix.wide.ad.jp
      PGADMIN_DEFAULT_PASSWORD: changeme
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  ipv6_gw:
    external: true

secrets:
  db_password:
    file: ./.secrets/db_password.txt

volumes:
  psql:
  pgadmin:
